# Generated by Django 3.1.4 on 2021-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20210102_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(default='example.com', max_length=254)),
                ('password', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'NOTAPPLICABEL')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(default='example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
