# Generated by Django 3.1.4 on 2021-01-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20210102_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
