# Generated by Django 3.1.4 on 2021-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_data',
            field=models.TextField(default=''),
        ),
    ]
