# Generated by Django 3.1.4 on 2021-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_complaint_complaint_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_data',
            field=models.TextField(),
        ),
    ]
